- name: creating user
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true
    
  - name: show the user_output
    ansible.builtin.debug:
      msg: "{{user_output}}"
  - name: create user if not exists
    ansible.builtin.command: useradd roboshop
    when:  user_output.rc != 1
    